version: '3.7'
services:
  web:
    image: infousuario_app:${TAG_IMAGEN}
    build: .
    container_name: infoUsuario_app
    restart: unless-stopped
    ports:
      - "1090:80"
    networks:
      - infoUsuario_app-network
    env_file:
      - .env
networks:
  infoUsuario_app-network:
    driver: bridge
    