version: '3.7'
services:
  web:
    image: infousuario_app:1.0
    build: .
    container_name: infoUsuario_app
    restart: unless-stopped
    ports:
      - "1090:80"
    networks:
      - infoUsuario_app-network
networks:
  infoUsuario_app-network:
    driver: bridge  